site_name: niri
docs_dir: wiki
site_url: https://niri-wm.github.io/niri
repo_url: https://github.com/niri-wm/niri
edit_uri: edit/main/docs/wiki/
use_directory_urls: false

theme:
  name: material
  logo: _assets/icons/logo.svg
  favicon: _assets/icons/logo.svg
  features:
    - search.suggest
    - content.code.copy
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme)"
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - attr_list
  - github-callouts
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - toc:
      permalink: '#'
plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: zh
          name: 简体中文
          build: true
          default: true
        - locale: en
          name: English
          build: true
      reconfigure_material: true
  - search
hooks:
  - hooks/shortcodes.py
  - hooks/remove-must-fail.py
extra_css:
  - _assets/stylesheets/niri.css
strict: true
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: relative_to_docs
  links:
    not_found: warn
    anchors: ignore
    absolute_links: relative_to_docs
    unrecognized_links: warn
not_in_nav: |
  zh/_Sidebar.md
  en/_Sidebar.md
  zh/Configuration:-Overview.md
  en/Configuration:-Overview.md
# ah, wouldn't it be nice if we could autogenerate this with wiki/_Sidebar.md
nav:
  - Home: zh/README.md
  - Usage:
    - Getting Started: zh/Getting-Started.md
    - Example systemd Setup: zh/Example-systemd-Setup.md
    - Important Software: zh/Important-Software.md
    - Workspaces: zh/Workspaces.md
    - Floating Windows: zh/Floating-Windows.md
    - Tabs: zh/Tabs.md
    - Overview: zh/Overview.md
    - Screencasting: zh/Screencasting.md
    - Layer‐Shell Components: zh/Layer‐Shell-Components.md
    - IPC, niri msg: zh/IPC.md
    - Application-Specific Issues: zh/Application-Issues.md
    - Nvidia: zh/Nvidia.md
    - Xwayland: zh/Xwayland.md
    - Gestures: zh/Gestures.md
    - Fullscreen and Maximize: zh/Fullscreen-and-Maximize.md
    - Window Effects: zh/Window-Effects.md
    - Packaging niri: zh/Packaging-niri.md
    - Integrating niri: zh/Integrating-niri.md
    - Accessibility: zh/Accessibility.md
    - Name and Logo: zh/Name-and-Logo.md
    - FAQ: zh/FAQ.md
  - Configuration:
    - Introduction: zh/Configuration:-Introduction.md
    - Input: zh/Configuration:-Input.md
    - Outputs: zh/Configuration:-Outputs.md
    - Key Bindings: zh/Configuration:-Key-Bindings.md
    - Switch Events: zh/Configuration:-Switch-Events.md
    - Layout: zh/Configuration:-Layout.md
    - Named Workspaces: zh/Configuration:-Named-Workspaces.md
    - Miscellaneous: zh/Configuration:-Miscellaneous.md
    - Window Rules: zh/Configuration:-Window-Rules.md
    - Layer Rules: zh/Configuration:-Layer-Rules.md
    - Animations: zh/Configuration:-Animations.md
    - Gestures: zh/Configuration:-Gestures.md
    - Recent Windows: zh/Configuration:-Recent-Windows.md
    - Debug Options: zh/Configuration:-Debug-Options.md
    - Include: zh/Configuration:-Include.md
  - Development:
    - Design Principles: zh/Development:-Design-Principles.md
    - Developing niri: zh/Development:-Developing-niri.md
    - Documenting niri: zh/Development:-Documenting-niri.md
    - Fractional Layout: zh/Development:-Fractional-Layout.md
    - Redraw Loop: zh/Development:-Redraw-Loop.md
    - Animation Timing: zh/Development:-Animation-Timing.md
