site_name: niri
docs_dir: wiki
site_url: https://niri-wm.github.io/niri
repo_url: https://github.com/niri-wm/niri
edit_uri: edit/main/docs/wiki/
use_directory_urls: false

theme:
  name: material
  logo: _assets/icons/logo.svg
  favicon: _assets/icons/logo.svg
  features:
    - search.suggest
    - content.code.copy
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme)"
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - attr_list
  - github-callouts
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - toc:
      permalink: '#'
plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: zh
          name: 简体中文
          build: true
          default: true
          nav_translations:
            Home: 首页
            Usage: 使用指南
            Getting Started: 快速入门
            Example systemd Setup: systemd 配置示例
            Important Software: 重要软件
            Workspaces: 工作区
            Floating Windows: 浮动窗口
            Tabs: 标签页
            Overview: 桌面概览
            Screencasting: 屏幕录制
            Layer‐Shell Components: Layer-Shell 组件
            IPC, niri msg: IPC, niri msg
            Application-Specific Issues: 应用程序特定问题
            Nvidia: Nvidia
            Xwayland: Xwayland
            Gestures: 手势操作
            Fullscreen and Maximize: 全屏和最大化
            Window Effects: 窗口效果
            Packaging niri: 打包 niri
            Integrating niri: 集成 niri
            Security Model: 安全模型
            Accessibility: 无障碍
            Name and Logo: 名称与徽标
            FAQ: 常见问题
            Configuration: 配置
            Introduction: 简介
            Input: 输入
            Outputs: 输出
            Key Bindings: 按键绑定
            Switch Events: 开关事件
            Layout: 布局
            Named Workspaces: 命名工作区
            Miscellaneous: 杂项
            Window Rules: 窗口规则
            Layer Rules: 图层规则
            Animations: 动画
            Gestures: 手势
            Recent Windows: 最近窗口
            Debug Options: 调试选项
            Include: 包含
            Development: 开发
            Design Principles: 设计原则
            Developing niri: 开发 niri
            Documenting niri: 文档化 niri
            Releasing niri: 发布 niri
            Fractional Layout: 分数布局
            Redraw Loop: 重绘循环
            Animation Timing: 动画定时
        - locale: en
          name: English
          build: true
      reconfigure_material: true
  - search
hooks:
  - hooks/shortcodes.py
  - hooks/remove-must-fail.py
extra_css:
  - _assets/stylesheets/niri.css
strict: true
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: relative_to_docs
  links:
    not_found: warn
    anchors: ignore
    absolute_links: relative_to_docs
    unrecognized_links: warn
not_in_nav: |
  zh/_Sidebar.md
  en/_Sidebar.md
  zh/Configuration:-Overview.md
  en/Configuration:-Overview.md
# ah, wouldn't it be nice if we could autogenerate this with wiki/_Sidebar.md
nav:
  - Home: zh/README.md
  - Usage:
    - Getting Started: zh/Getting-Started.md
    - Example systemd Setup: zh/Example-systemd-Setup.md
    - Important Software: zh/Important-Software.md
    - Workspaces: zh/Workspaces.md
    - Floating Windows: zh/Floating-Windows.md
    - Tabs: zh/Tabs.md
    - Overview: zh/Overview.md
    - Screencasting: zh/Screencasting.md
    - Layer‐Shell Components: zh/Layer‐Shell-Components.md
    - IPC, niri msg: zh/IPC.md
    - Application-Specific Issues: zh/Application-Issues.md
    - Nvidia: zh/Nvidia.md
    - Xwayland: zh/Xwayland.md
    - Gestures: zh/Gestures.md
    - Fullscreen and Maximize: zh/Fullscreen-and-Maximize.md
    - Window Effects: zh/Window-Effects.md
    - Packaging niri: zh/Packaging-niri.md
    - Integrating niri: zh/Integrating-niri.md
    - Security Model: zh/Security-Model.md
    - Accessibility: zh/Accessibility.md
    - Name and Logo: zh/Name-and-Logo.md
    - FAQ: zh/FAQ.md
  - Configuration:
    - Introduction: zh/Configuration:-Introduction.md
    - Input: zh/Configuration:-Input.md
    - Outputs: zh/Configuration:-Outputs.md
    - Key Bindings: zh/Configuration:-Key-Bindings.md
    - Switch Events: zh/Configuration:-Switch-Events.md
    - Layout: zh/Configuration:-Layout.md
    - Named Workspaces: zh/Configuration:-Named-Workspaces.md
    - Miscellaneous: zh/Configuration:-Miscellaneous.md
    - Window Rules: zh/Configuration:-Window-Rules.md
    - Layer Rules: zh/Configuration:-Layer-Rules.md
    - Animations: zh/Configuration:-Animations.md
    - Gestures: zh/Configuration:-Gestures.md
    - Recent Windows: zh/Configuration:-Recent-Windows.md
    - Debug Options: zh/Configuration:-Debug-Options.md
    - Include: zh/Configuration:-Include.md
  - Development:
    - Design Principles: zh/Development:-Design-Principles.md
    - Developing niri: zh/Development:-Developing-niri.md
    - Documenting niri: zh/Development:-Documenting-niri.md
    - Releasing niri: zh/Development:-Releasing-niri.md
    - Fractional Layout: zh/Development:-Fractional-Layout.md
    - Redraw Loop: zh/Development:-Redraw-Loop.md
    - Animation Timing: zh/Development:-Animation-Timing.md
